export enum Validators {
  OPTIONAL = 'optional',
  REQUIRED = 'required',
  REQUIRED_IF = 'requiredIf',
  REQUIRED_UNLESS = 'requiredUnless',
  MIN_LENGTH = 'minLength',
  MAX_LENGTH = 'maxLength',
  MIN_VALUE = 'minValue',
  MAX_VALUE = 'maxValue',
  BETWEEN = 'between',
  ALPHA = 'alpha',
  ALPHA_NUM = 'alphaNum',
  NUMERIC = 'numeric',
  INTEGER = 'integer',
  DECIMAL = 'decimal',
  EMAIL = 'email',
  IP_ADDRESS = 'ipAddress',
  MAC_ADDRESS = 'macAddress',
  SAME_AS = 'sameAs',
  URL = 'url',
  OR = 'or',
  AND = 'and',
  NOT = 'not',
  CUSTOM = 'custom',
}
